[build]
  command = "npm install"
  functions = "functions"
  publish = "public"

[functions]
  included_files = ["views/**", "labs/**", "data/**"]
  node_bundler = "esbuild"
  external_node_modules = ["express", "cookie-parser", "express-session", "sqlite3", "uuid", "ejs"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
  force = true
